version: '3'

services:
  glances:
    image: nicolargo/glances:latest-alpine
    container_name: glances
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"

networks:
  default:
    name: nginx
    external: true
